app:
  url: http://dev.local/v1/documents
db:
  prefix: mongodb
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  host: localhost
  port: 27017
  name: documents
  timeout: 10
server:
  port: 8080
  timeout: 20
log:
  debug: false
shortlink:
  apikey: ${SHORTLINK_APIKEY}
  domain: tiny.one
